project:
  type: website
  output-dir: blog

website:
  title: "Anvit Aggarwal"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: blog
        text: Blog

format:
  html:
    theme: cosmo
    css: styles.css

